# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa8d23da1e43acab8ca38562ead53918505c5e5f255ad1b28598fe18da3a7f2630d135954ab6a8ecc5d7661c2ff899620f5d12f076e42d74b5d27b59b55fb02
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 590a067280d401edb42bf386e35ca7de542dd19b284eef7f70cafe8e36b1b719555ec94ff0750eb09562614dbcb59bfbc0de2720e3e524f1cdb1fa856bb713bb

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>